import { SymbolView } from 'expo-symbols';
import type { ComponentProps } from 'react';
import { Text, type ColorValue, type StyleProp, type ViewStyle } from 'react-native';

export type IconName = 'home' | 'grid' | 'heart' | 'receipt' | 'user' | 'search' | 'filter' | 'bell' | 'cart' | 'chevron-right' | 'arrow-left' | 'star' | 'plus' | 'minus' | 'trash' | 'check' | 'location' | 'store' | 'card' | 'cash' | 'tag' | 'note' | 'lock' | 'logout' | 'edit' | 'camera' | 'mail' | 'phone' | 'clock' | 'truck' | 'box' | 'shield' | 'eye' | 'eye-off' | 'close' | 'refresh' | 'laptop' | 'flash' | 'sliders' | 'check-circle' | 'warning' | 'info' | 'share' | 'message';

const names: Record<IconName, ComponentProps<typeof SymbolView>['name']> = {
  home: { ios: 'house.fill', android: 'home', web: 'home' }, grid: { ios: 'square.grid.2x2.fill', android: 'grid_view', web: 'grid_view' }, heart: { ios: 'heart.fill', android: 'favorite', web: 'favorite' }, receipt: { ios: 'shippingbox.fill', android: 'receipt_long', web: 'receipt_long' }, user: { ios: 'person.fill', android: 'person', web: 'person' }, search: { ios: 'magnifyingglass', android: 'search', web: 'search' }, filter: { ios: 'line.3.horizontal.decrease', android: 'filter_alt', web: 'filter_alt' }, bell: { ios: 'bell.fill', android: 'notifications', web: 'notifications' }, cart: { ios: 'cart.fill', android: 'shopping_cart', web: 'shopping_cart' },
  'chevron-right': { ios: 'chevron.right', android: 'chevron_right', web: 'chevron_right' }, 'arrow-left': { ios: 'arrow.left', android: 'arrow_back', web: 'arrow_back' }, star: { ios: 'star.fill', android: 'star', web: 'star' }, plus: { ios: 'plus', android: 'add', web: 'add' }, minus: { ios: 'minus', android: 'remove', web: 'remove' }, trash: { ios: 'trash.fill', android: 'delete', web: 'delete' }, check: { ios: 'checkmark', android: 'check', web: 'check' }, location: { ios: 'mappin.and.ellipse', android: 'location_on', web: 'location_on' }, store: { ios: 'storefront.fill', android: 'storefront', web: 'storefront' }, card: { ios: 'creditcard.fill', android: 'credit_card', web: 'credit_card' }, cash: { ios: 'banknote.fill', android: 'payments', web: 'payments' }, tag: { ios: 'tag.fill', android: 'sell', web: 'sell' }, note: { ios: 'note.text', android: 'notes', web: 'notes' }, lock: { ios: 'lock.fill', android: 'lock', web: 'lock' }, logout: { ios: 'rectangle.portrait.and.arrow.right', android: 'logout', web: 'logout' }, edit: { ios: 'pencil', android: 'edit', web: 'edit' }, camera: { ios: 'camera.fill', android: 'photo_camera', web: 'photo_camera' }, mail: { ios: 'envelope.fill', android: 'mail', web: 'mail' }, phone: { ios: 'phone.fill', android: 'call', web: 'call' }, clock: { ios: 'clock.fill', android: 'schedule', web: 'schedule' }, truck: { ios: 'truck.box.fill', android: 'local_shipping', web: 'local_shipping' }, box: { ios: 'shippingbox.fill', android: 'inventory_2', web: 'inventory_2' }, shield: { ios: 'shield.checkered', android: 'verified_user', web: 'verified_user' }, eye: { ios: 'eye.fill', android: 'visibility', web: 'visibility' }, 'eye-off': { ios: 'eye.slash.fill', android: 'visibility_off', web: 'visibility_off' }, close: { ios: 'xmark', android: 'close', web: 'close' }, refresh: { ios: 'arrow.clockwise', android: 'refresh', web: 'refresh' }, laptop: { ios: 'laptopcomputer', android: 'laptop_mac', web: 'laptop_mac' }, flash: { ios: 'bolt.fill', android: 'bolt', web: 'bolt' }, sliders: { ios: 'slider.horizontal.3', android: 'tune', web: 'tune' }, 'check-circle': { ios: 'checkmark.circle.fill', android: 'check_circle', web: 'check_circle' }, warning: { ios: 'exclamationmark.triangle.fill', android: 'warning', web: 'warning' }, info: { ios: 'info.circle.fill', android: 'info', web: 'info' }, share: { ios: 'square.and.arrow.up', android: 'share', web: 'share' }, message: { ios: 'message.fill', android: 'chat', web: 'chat' },
};

interface IconProps { name: IconName; size?: number; color?: ColorValue; style?: StyleProp<ViewStyle> }
export function Icon({ name, size = 22, color = '#182230', style }: IconProps) {
  return <SymbolView name={names[name]} size={size} tintColor={color} style={style} fallback={<Text style={{ color, fontSize: size * 0.72, fontWeight: '800' }}>•</Text>} />;
}
