import { EmptyState } from '@/components/empty-state';
import { Button } from '@/components/ui/button';
import { Icon } from '@/components/ui/icon';
import { ScreenHeader } from '@/components/ui/screen-header';
import { colors, layout, radius, spacing, typography } from '@/constants/theme';
import { addresses as seedAddresses } from '@/data/mock-data';
import { useApp } from '@/state/app-context';
import type { Address } from '@/types';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { useState } from 'react';

export default function AddressesScreen() {
  const { notify } = useApp(); const [items, setItems] = useState<Address[]>(seedAddresses);
  const add = () => { if (items.some((item) => item.id === 'demo')) return notify('Địa chỉ mẫu đã được thêm'); setItems((current) => [...current, { id: 'demo', recipient: 'Nguyễn Văn An', phone: '090 123 4567', detail: '45 Lê Lợi, P. Bến Nghé, Quận 1, TP. Hồ Chí Minh', isDefault: false }]); notify('Đã thêm địa chỉ mẫu'); };
  const remove = (id: string) => Alert.alert('Xóa địa chỉ', 'Bạn có chắc muốn xóa địa chỉ này?', [{ text: 'Không', style: 'cancel' }, { text: 'Xóa', style: 'destructive', onPress: () => setItems((current) => current.filter((item) => item.id !== id)) }]);
  return <View style={styles.page}><ScreenHeader title="Sổ địa chỉ" /><FlatList data={items} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, !items.length && styles.empty]} renderItem={({ item }) => <View style={styles.card}><View style={styles.cardTop}><View style={styles.pin}><Icon name="location" color={colors.primary} /></View><View style={styles.copy}><View style={styles.nameRow}><Text style={styles.name}>{item.recipient}</Text><Text style={styles.phone}>{item.phone}</Text></View><Text style={styles.address}>{item.detail}</Text>{item.isDefault && <View style={styles.default}><Text style={styles.defaultText}>Mặc định</Text></View>}</View></View><View style={styles.actions}><Pressable onPress={() => notify('Đã mở chỉnh sửa địa chỉ')} style={styles.action}><Icon name="edit" size={17} color={colors.primary} /><Text style={styles.editText}>Chỉnh sửa</Text></Pressable>{!item.isDefault && <><Pressable onPress={() => setItems((current) => current.map((address) => ({ ...address, isDefault: address.id === item.id })))}><Text style={styles.defaultAction}>Đặt mặc định</Text></Pressable><Pressable onPress={() => remove(item.id)}><Icon name="trash" size={18} color={colors.danger} /></Pressable></>}</View></View>} ListEmptyComponent={<EmptyState icon="location" title="Chưa có địa chỉ" description="Thêm địa chỉ để thanh toán nhanh hơn." />} ListFooterComponent={<Button title="Thêm địa chỉ mới" icon="plus" variant="outline" onPress={add} style={styles.add} />} /></View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', padding: spacing.lg, gap: spacing.md }, empty: { flexGrow: 1 }, card: { backgroundColor: colors.white, borderRadius: radius.lg, borderWidth: 1, borderColor: colors.border, padding: spacing.lg }, cardTop: { flexDirection: 'row', gap: spacing.md }, pin: { width: 42, height: 42, borderRadius: 13, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, copy: { flex: 1 }, nameRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm }, name: { ...typography.bodyMedium, color: colors.text }, phone: { ...typography.caption, color: colors.textSecondary }, address: { ...typography.caption, color: colors.textSecondary, marginTop: 5 }, default: { alignSelf: 'flex-start', marginTop: spacing.sm, paddingHorizontal: spacing.sm, paddingVertical: 3, borderRadius: radius.sm, backgroundColor: colors.primarySoft }, defaultText: { ...typography.tiny, color: colors.primary }, actions: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingTop: spacing.md, marginTop: spacing.md, borderTopWidth: 1, borderTopColor: colors.border }, action: { flexDirection: 'row', alignItems: 'center', gap: 5 }, editText: { ...typography.captionMedium, color: colors.primary }, defaultAction: { ...typography.captionMedium, color: colors.textSecondary }, add: { marginTop: spacing.sm } });
