import { EmptyState } from '@/components/empty-state';
import { ProductImage } from '@/components/product-image';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Icon } from '@/components/ui/icon';
import { QuantityStepper } from '@/components/ui/quantity-stepper';
import { ScreenHeader } from '@/components/ui/screen-header';
import { colors, layout, radius, spacing, typography } from '@/constants/theme';
import { useApp } from '@/state/app-context';
import { formatCurrency } from '@/utils/format';
import { useRouter } from 'expo-router';
import { Alert, FlatList, Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

export default function CartScreen() {
  const router = useRouter(); const insets = useSafeAreaInsets(); const { cart, selectedTotal, toggleAllCart, toggleCartItem, updateQuantity, removeFromCart } = useApp(); const selected = cart.filter((item) => item.selected).length;
  const remove = (id: string) => Alert.alert('Xóa sản phẩm', 'Bạn muốn xóa sản phẩm này khỏi giỏ hàng?', [{ text: 'Không', style: 'cancel' }, { text: 'Xóa', style: 'destructive', onPress: () => removeFromCart(id) }]);
  return <View style={styles.page}><ScreenHeader title="Giỏ hàng" subtitle={`${cart.length} sản phẩm`} /><FlatList data={cart} keyExtractor={(item) => item.product.id} contentContainerStyle={[styles.content, !cart.length && styles.empty, { paddingBottom: 122 + insets.bottom }]} ListHeaderComponent={cart.length ? <View style={styles.selectAll}><Checkbox checked={selected === cart.length} onPress={toggleAllCart} /><Text style={styles.selectText}>Chọn tất cả ({cart.length})</Text></View> : null} renderItem={({ item }) => <View style={styles.item}><Checkbox checked={item.selected} onPress={() => toggleCartItem(item.product.id)} /><ProductImage uri={item.product.image} style={styles.image} /><View style={styles.copy}><View style={styles.nameRow}><Text numberOfLines={2} style={styles.name}>{item.product.name}</Text><Pressable onPress={() => remove(item.product.id)} hitSlop={8}><Icon name="trash" size={19} color={colors.textMuted} /></Pressable></View><Text style={styles.spec}>{item.product.specs.ram} · {item.product.specs.ssd}</Text><View style={styles.bottomRow}><Text style={styles.price}>{formatCurrency(item.product.price)}</Text><QuantityStepper value={item.quantity} onChange={(value) => updateQuantity(item.product.id, value)} /></View></View></View>} ListEmptyComponent={<EmptyState icon="cart" title="Giỏ hàng đang trống" description="Khám phá những mẫu laptop phù hợp và thêm vào giỏ hàng." action="Tiếp tục mua sắm" onAction={() => router.push('/products')} />} />{cart.length > 0 && <View style={[styles.footer, { paddingBottom: Math.max(insets.bottom, spacing.md) }]}><View style={styles.totalRow}><View><Text style={styles.totalLabel}>Tổng cộng ({selected})</Text><Text style={styles.total}>{formatCurrency(selectedTotal)}</Text></View><Text style={styles.shipping}>Miễn phí vận chuyển</Text></View><Button title="Tiến hành thanh toán" disabled={!selected} onPress={() => router.push('/checkout')} /></View>}</View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', padding: spacing.lg, gap: spacing.md }, empty: { flexGrow: 1 }, selectAll: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm, paddingBottom: spacing.xs }, selectText: { ...typography.captionMedium, color: colors.text }, item: { flexDirection: 'row', alignItems: 'center', gap: spacing.md, backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.md, borderWidth: 1, borderColor: colors.border }, image: { width: 88, height: 82, borderRadius: radius.md, backgroundColor: colors.surfaceAlt }, copy: { flex: 1, alignSelf: 'stretch', justifyContent: 'space-between' }, nameRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.xs }, name: { ...typography.captionMedium, color: colors.text, flex: 1 }, spec: { ...typography.tiny, color: colors.textSecondary }, bottomRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, price: { ...typography.bodyMedium, color: colors.danger }, footer: { position: 'absolute', left: 0, right: 0, bottom: 0, backgroundColor: colors.white, borderTopWidth: 1, borderTopColor: colors.border, padding: spacing.md, gap: spacing.md }, totalRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-end' }, totalLabel: { ...typography.caption, color: colors.textSecondary }, total: { ...typography.h2, color: colors.danger }, shipping: { ...typography.tiny, color: colors.success } });
