import { EmptyState } from '@/components/empty-state';
import { Icon, type IconName } from '@/components/ui/icon';
import { ScreenHeader } from '@/components/ui/screen-header';
import { colors, layout, radius, spacing, typography } from '@/constants/theme';
import { initialNotifications } from '@/data/mock-data';
import { useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, View } from 'react-native';

export default function NotificationsScreen() {
  const [data, setData] = useState(initialNotifications); const unread = data.filter((item) => !item.read).length; const markAll = () => setData((items) => items.map((item) => ({ ...item, read: true })));
  return <View style={styles.page}><ScreenHeader title="Thông báo" subtitle={`${unread} chưa đọc`} rightIcon="check" onRightPress={markAll} /><FlatList data={data} keyExtractor={(item) => item.id} contentContainerStyle={[styles.content, !data.length && styles.empty]} renderItem={({ item }) => <Pressable onPress={() => setData((items) => items.map((value) => value.id === item.id ? { ...value, read: true } : value))} style={[styles.item, !item.read && styles.unread]}><View style={[styles.icon, item.type === 'promotion' && styles.promotion]}><Icon name={(item.type === 'order' ? 'box' : item.type === 'promotion' ? 'tag' : 'info') as IconName} size={21} color={item.type === 'promotion' ? colors.danger : colors.primary} /></View><View style={styles.copy}><View style={styles.titleRow}><Text style={styles.title}>{item.title}</Text>{!item.read && <View style={styles.dot} />}</View><Text style={styles.message}>{item.message}</Text><Text style={styles.time}>{item.time}</Text></View></Pressable>} ListEmptyComponent={<EmptyState icon="bell" title="Không có thông báo" description="Thông báo về đơn hàng và ưu đãi sẽ xuất hiện tại đây." />} /></View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', padding: spacing.lg, gap: spacing.sm }, empty: { flexGrow: 1 }, item: { flexDirection: 'row', gap: spacing.md, padding: spacing.lg, borderRadius: radius.lg, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border }, unread: { borderColor: '#C8D5FF', backgroundColor: '#F8FAFF' }, icon: { width: 44, height: 44, borderRadius: 14, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center' }, promotion: { backgroundColor: colors.dangerSoft }, copy: { flex: 1 }, titleRow: { flexDirection: 'row', alignItems: 'center' }, title: { ...typography.bodyMedium, color: colors.text, flex: 1 }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primary }, message: { ...typography.caption, color: colors.textSecondary, marginTop: 3 }, time: { ...typography.tiny, color: colors.textMuted, marginTop: 6 } });
