import type { ManagementConfig, StatusTone } from '../types/admin'

export const statusTones: Record<string, StatusTone> = {
  'Đã giao': 'success', 'Hoàn tất': 'success', 'Đã duyệt': 'success', 'Đang hoạt động': 'success', 'Hiển thị': 'success', 'Đã gửi': 'success',
  'Đang xử lý': 'info', 'Đang giao': 'purple', 'Sắp diễn ra': 'purple', 'Chờ duyệt': 'warning', 'Chờ xác nhận': 'warning', 'Sắp hết': 'warning',
  'Thất bại': 'danger', 'Đã hủy': 'danger', 'Hết hàng': 'danger', 'Tạm khóa': 'danger', 'Đã ẩn': 'neutral', 'Nháp': 'neutral', 'Ngừng hợp tác': 'neutral',
}

function basic(title: string, eyebrow: string, description: string, entityName: string, labels: string[], data: string[][], moneyIndex = -1): ManagementConfig {
  const keys = labels.map((_, index) => `c${index}`)
  return { title, eyebrow, description, entityName, addLabel: `Thêm ${entityName}`, searchPlaceholder: `Tìm kiếm ${entityName}...`,
    columns: labels.map((label, index) => ({ key: keys[index], label, type: index === labels.length - 1 ? 'status' : index === moneyIndex ? 'money' : index === 0 && ['Khách hàng', 'Nhân viên'].some((term) => label.includes(term)) ? 'user' : 'text' })),
    rows: data.map((values, rowIndex) => Object.fromEntries([['id', `${rowIndex + 1}`], ...values.map((value, index) => [keys[index], moneyIndex === index ? Number(value) : value])])), filters: ['Tất cả trạng thái', 'Đang hoạt động', 'Chờ xử lý'] }
}

export const managementConfigs: Record<string, ManagementConfig> = {
  '/san-pham': { title: 'Sản phẩm Laptop', eyebrow: 'Quản lý sản phẩm', description: 'Quản lý thông tin, giá bán, hình ảnh và trạng thái sản phẩm.', addLabel: 'Thêm Laptop', searchPlaceholder: 'Tìm tên, SKU sản phẩm...', entityName: 'sản phẩm', filters: ['Tất cả hãng', 'Apple', 'Dell', 'ASUS', 'Lenovo', 'HP'],
    stats: [{ label: 'Tổng sản phẩm', value: '326', note: '284 đang hiển thị', tone: 'info' }, { label: 'Sắp hết hàng', value: '18', note: 'Cần nhập thêm', tone: 'warning' }, { label: 'Hết hàng', value: '7', note: 'Cần xử lý', tone: 'danger' }],
    columns: [{ key: 'name', label: 'Sản phẩm', type: 'product' }, { key: 'category', label: 'Danh mục' }, { key: 'price', label: 'Giá bán', type: 'money' }, { key: 'stock', label: 'Tồn kho' }, { key: 'status', label: 'Trạng thái', type: 'status' }],
    rows: [{ id: 'SP001', name: 'MacBook Air M3 13 inch 8GB/256GB', sku: 'MBA-M3-256', category: 'MacBook', price: 27990000, stock: 24, status: 'Hiển thị' }, { id: 'SP002', name: 'ASUS ROG Zephyrus G14 2026', sku: 'ROG-G14-26', category: 'Gaming', price: 45990000, stock: 4, status: 'Sắp hết' }, { id: 'SP003', name: 'Dell XPS 13 Plus 9320', sku: 'XPS13-9320', category: 'Ultrabook', price: 32990000, stock: 18, status: 'Hiển thị' }, { id: 'SP004', name: 'Lenovo ThinkPad X1 Carbon Gen 12', sku: 'X1C-G12', category: 'Doanh nhân', price: 38990000, stock: 0, status: 'Hết hàng' }, { id: 'SP005', name: 'HP Victus 16 RTX 4060', sku: 'HP-V16-4060', category: 'Gaming', price: 29490000, stock: 12, status: 'Đã ẩn' }] },
  '/don-hang': { title: 'Quản lý đơn hàng', eyebrow: 'Bán hàng', description: 'Theo dõi, xác nhận và cập nhật tiến trình xử lý đơn hàng.', addLabel: 'Tạo đơn hàng', searchPlaceholder: 'Tìm mã đơn, khách hàng...', entityName: 'đơn hàng', filters: ['Tất cả trạng thái', 'Chờ xác nhận', 'Đang xử lý', 'Đang giao', 'Đã giao', 'Đã hủy'],
    stats: [{ label: 'Đơn hôm nay', value: '46', note: '+12,5% so với hôm qua', tone: 'info' }, { label: 'Chờ xử lý', value: '12', note: '3 đơn ưu tiên', tone: 'warning' }, { label: 'Doanh thu hôm nay', value: '186,4 tr', note: '38 đơn đã thanh toán', tone: 'success' }],
    columns: [{ key: 'code', label: 'Mã đơn' }, { key: 'customer', label: 'Khách hàng', type: 'user' }, { key: 'date', label: 'Ngày đặt' }, { key: 'total', label: 'Tổng tiền', type: 'money' }, { key: 'payment', label: 'Thanh toán' }, { key: 'status', label: 'Trạng thái', type: 'status' }],
    rows: [{ id: '1', code: '#LZ-10428', customer: 'Nguyễn Minh Anh', secondary: 'minhanh@gmail.com', date: '19/09/2026 · 09:42', total: 25990000, payment: 'VNPay', status: 'Đã giao' }, { id: '2', code: '#LZ-10427', customer: 'Trần Quốc Bảo', secondary: '0903 456 789', date: '19/09/2026 · 09:18', total: 18490000, payment: 'COD', status: 'Đang xử lý' }, { id: '3', code: '#LZ-10426', customer: 'Lê Hoàng Nam', secondary: 'hoangnam@gmail.com', date: '19/09/2026 · 08:55', total: 32990000, payment: 'Chuyển khoản', status: 'Chờ xác nhận' }, { id: '4', code: '#LZ-10425', customer: 'Phạm Thu Hà', secondary: 'thuha@gmail.com', date: '18/09/2026 · 21:26', total: 21490000, payment: 'VNPay', status: 'Đang giao' }, { id: '5', code: '#LZ-10424', customer: 'Vũ Đức Long', secondary: '0912 882 114', date: '18/09/2026 · 20:14', total: 45990000, payment: 'COD', status: 'Đã hủy' }] },
  '/thanh-toan': basic('Quản lý thanh toán', 'Bán hàng', 'Theo dõi giao dịch và đối soát các phương thức thanh toán.', 'giao dịch', ['Mã giao dịch', 'Đơn hàng', 'Khách hàng', 'Số tiền', 'Phương thức', 'Trạng thái'], [['TXN-982451', '#LZ-10428', 'Nguyễn Minh Anh', '25990000', 'VNPay', 'Hoàn tất'], ['TXN-982450', '#LZ-10427', 'Trần Quốc Bảo', '18490000', 'COD', 'Chờ xác nhận'], ['TXN-982449', '#LZ-10426', 'Lê Hoàng Nam', '32990000', 'Chuyển khoản', 'Hoàn tất'], ['TXN-982448', '#LZ-10422', 'Đặng Mỹ Linh', '12990000', 'VNPay', 'Thất bại']], 3),
  '/danh-gia': basic('Quản lý đánh giá', 'Bán hàng', 'Kiểm duyệt phản hồi và duy trì chất lượng nội dung.', 'đánh giá', ['Khách hàng', 'Sản phẩm', 'Đánh giá', 'Ngày gửi', 'Trạng thái'], [['Hoàng Gia Huy', 'MacBook Air M3', '5 / 5 · Rất hài lòng', '19/09/2026', 'Chờ duyệt'], ['Ngọc Thanh', 'ASUS ROG G14', '4 / 5 · Máy chạy tốt', '18/09/2026', 'Đã duyệt'], ['Minh Khang', 'Dell XPS 13 Plus', '3 / 5 · Giao hàng chậm', '18/09/2026', 'Chờ duyệt']]),
  '/danh-muc': basic('Danh mục sản phẩm', 'Quản lý sản phẩm', 'Tổ chức danh mục giúp khách hàng tìm sản phẩm nhanh hơn.', 'danh mục', ['Tên danh mục', 'Mã', 'Số sản phẩm', 'Thứ tự', 'Trạng thái'], [['Laptop Gaming', 'GAMING', '84', '01', 'Đang hoạt động'], ['Laptop Văn phòng', 'OFFICE', '96', '02', 'Đang hoạt động'], ['Laptop Đồ họa', 'GRAPHIC', '53', '03', 'Đang hoạt động'], ['MacBook', 'MACBOOK', '28', '04', 'Đang hoạt động']]),
  '/hang-laptop': basic('Hãng Laptop', 'Quản lý sản phẩm', 'Quản lý thương hiệu và danh mục sản phẩm tương ứng.', 'hãng', ['Tên hãng', 'Xuất xứ', 'Số sản phẩm', 'Ngày cập nhật', 'Trạng thái'], [['Apple', 'Hoa Kỳ', '28', '18/09/2026', 'Đang hoạt động'], ['Dell', 'Hoa Kỳ', '52', '17/09/2026', 'Đang hoạt động'], ['ASUS', 'Đài Loan', '61', '16/09/2026', 'Đang hoạt động'], ['Lenovo', 'Trung Quốc', '48', '15/09/2026', 'Đang hoạt động']]),
  '/kho-hang': basic('Kho & tồn kho', 'Kho hàng', 'Theo dõi tồn thực tế, mức cảnh báo và vị trí lưu kho.', 'mặt hàng', ['Sản phẩm', 'SKU', 'Kho chính', 'Đang giữ', 'Khả dụng', 'Trạng thái'], [['MacBook Air M3 13 inch', 'MBA-M3-256', '24', '3', '21', 'Đang hoạt động'], ['ASUS ROG Zephyrus G14', 'ROG-G14-26', '4', '2', '2', 'Sắp hết'], ['Dell XPS 13 Plus', 'XPS13-9320', '18', '1', '17', 'Đang hoạt động'], ['ThinkPad X1 Carbon', 'X1C-G12', '0', '0', '0', 'Hết hàng']]),
  '/phieu-nhap': basic('Phiếu nhập kho', 'Kho hàng', 'Quản lý lô hàng nhập và tiến trình kiểm kho.', 'phiếu nhập', ['Mã phiếu', 'Nhà cung cấp', 'Ngày nhập', 'Số lượng', 'Tổng giá trị', 'Trạng thái'], [['#PN-260919', 'Digiworld', '19/09/2026', '42', '986500000', 'Chờ xác nhận'], ['#PN-260915', 'FPT Synnex', '15/09/2026', '68', '1428000000', 'Hoàn tất'], ['#PN-260910', 'Petrosetco', '10/09/2026', '35', '724000000', 'Hoàn tất']], 4),
  '/nha-cung-cap': basic('Nhà cung cấp', 'Kho hàng', 'Quản lý đối tác, thông tin liên hệ và lịch sử nhập hàng.', 'nhà cung cấp', ['Nhà cung cấp', 'Người liên hệ', 'Điện thoại', 'Số phiếu nhập', 'Trạng thái'], [['Digiworld', 'Nguyễn Hồng Phúc', '028 3820 8888', '38', 'Đang hoạt động'], ['FPT Synnex', 'Trần Minh Quang', '028 7300 2222', '46', 'Đang hoạt động'], ['Petrosetco', 'Lê Ngọc Hân', '028 3911 6868', '21', 'Đang hoạt động'], ['Tech Data Việt Nam', 'Phạm Quốc Huy', '028 3824 6677', '8', 'Ngừng hợp tác']]),
  '/khuyen-mai': basic('Chương trình khuyến mãi', 'Marketing', 'Thiết lập ưu đãi, mã giảm giá và thời gian áp dụng.', 'khuyến mãi', ['Tên chương trình', 'Mã', 'Ưu đãi', 'Thời gian', 'Lượt dùng', 'Trạng thái'], [['Back to School 2026', 'BTS2026', 'Giảm 10%', '01/09 - 30/09', '284 / 500', 'Đang hoạt động'], ['Ưu đãi khách mới', 'WELCOME500', 'Giảm 500.000đ', 'Không giới hạn', '128', 'Đang hoạt động'], ['Flash Sale cuối tuần', 'WEEKEND', 'Giảm 8%', '26/09 - 27/09', '0 / 200', 'Sắp diễn ra']]),
  '/banner': basic('Banner quảng cáo', 'Marketing', 'Quản lý nội dung hiển thị trên ứng dụng và website.', 'banner', ['Tên banner', 'Vị trí', 'Thời gian hiển thị', 'Lượt nhấp', 'Trạng thái'], [['MacBook Air M3', 'Trang chủ · Hero', '01/09 - 30/09', '4.286', 'Hiển thị'], ['Laptop Gaming RTX 40', 'Trang chủ · Giữa trang', '10/09 - 25/09', '2.104', 'Hiển thị'], ['Back to School', 'Danh mục', '01/09 - 15/09', '1.842', 'Đã ẩn']]),
  '/thong-bao': basic('Thông báo', 'Marketing', 'Soạn và quản lý thông báo gửi đến người dùng.', 'thông báo', ['Tiêu đề', 'Đối tượng', 'Kênh', 'Ngày gửi', 'Trạng thái'], [['Flash Sale cuối tuần', 'Tất cả khách hàng', 'Push notification', '19/09/2026 · 10:00', 'Đã gửi'], ['Đơn hàng đã giao', 'Khách có đơn hàng', 'Email + Push', 'Tự động', 'Đang hoạt động'], ['Sản phẩm mới tháng 9', 'Khách hàng VIP', 'Email', '20/09/2026 · 08:00', 'Nháp']]),
  '/khach-hang': basic('Khách hàng', 'Người dùng', 'Quản lý hồ sơ và lịch sử mua hàng của khách hàng.', 'khách hàng', ['Khách hàng', 'Điện thoại', 'Đơn hàng', 'Tổng chi tiêu', 'Ngày tham gia', 'Trạng thái'], [['Nguyễn Minh Anh', '0903 123 456', '12', '186400000', '12/02/2026', 'Đang hoạt động'], ['Trần Quốc Bảo', '0918 456 789', '8', '122900000', '04/03/2026', 'Đang hoạt động'], ['Lê Hoàng Nam', '0987 234 567', '5', '98400000', '18/04/2026', 'Đang hoạt động'], ['Phạm Thu Hà', '0908 111 222', '3', '47600000', '25/06/2026', 'Tạm khóa']], 3),
  '/nhan-vien': basic('Nhân viên', 'Người dùng', 'Quản lý đội ngũ vận hành và phạm vi làm việc.', 'nhân viên', ['Nhân viên', 'Mã NV', 'Chức vụ', 'Điện thoại', 'Ngày vào làm', 'Trạng thái'], [['Nguyễn Thanh Tùng', 'NV-0018', 'Quản lý bán hàng', '0909 112 233', '10/01/2025', 'Đang hoạt động'], ['Trần Khánh Linh', 'NV-0021', 'Nhân viên kho', '0912 445 566', '15/04/2025', 'Đang hoạt động'], ['Phạm Minh Đức', 'NV-0026', 'CSKH', '0988 778 899', '02/08/2025', 'Đang hoạt động']]),
  '/tai-khoan': basic('Tài khoản & phân quyền', 'Người dùng', 'Kiểm soát tài khoản nội bộ và vai trò truy cập hệ thống.', 'tài khoản', ['Tài khoản', 'Vai trò', 'Phạm vi', 'Lần đăng nhập cuối', 'Trạng thái'], [['admin@lapzone.vn', 'Super Admin', 'Toàn bộ hệ thống', '19/09/2026 · 09:30', 'Đang hoạt động'], ['sales@lapzone.vn', 'Quản lý bán hàng', 'Đơn hàng, thanh toán', '19/09/2026 · 08:45', 'Đang hoạt động'], ['warehouse@lapzone.vn', 'Quản lý kho', 'Kho hàng, phiếu nhập', '18/09/2026 · 17:28', 'Đang hoạt động']]),
}
