import { AuthShell } from '@/components/auth-shell';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { FormField } from '@/components/ui/form-field';
import { colors, spacing, typography } from '@/constants/theme';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';

export default function RegisterScreen() {
  const router = useRouter(); const [form, setForm] = useState({ name: '', username: '', phone: '', email: '', password: '', confirm: '' }); const [agreed, setAgreed] = useState(false); const update = (key: keyof typeof form) => (value: string) => setForm((current) => ({ ...current, [key]: value })); const valid = form.name.trim() && form.username.trim() && /^0\d{9}$/.test(form.phone) && form.email.includes('@') && form.password.length >= 8 && form.password === form.confirm && agreed;
  return <AuthShell title="Tạo tài khoản LapZone" subtitle="Đăng ký nhanh để nhận ưu đãi thành viên"><View style={styles.form}><FormField label="Họ và tên" icon="user" value={form.name} onChangeText={update('name')} placeholder="Nguyễn Văn An" /><FormField label="Tên đăng nhập" icon="user" value={form.username} onChangeText={update('username')} autoCapitalize="none" placeholder="nguyenvanan" /><FormField label="Số điện thoại" icon="phone" value={form.phone} onChangeText={update('phone')} keyboardType="phone-pad" placeholder="0901234567" /><FormField label="Email" icon="mail" value={form.email} onChangeText={update('email')} keyboardType="email-address" autoCapitalize="none" placeholder="email@example.com" /><FormField label="Mật khẩu" icon="lock" value={form.password} onChangeText={update('password')} secureTextEntry placeholder="Tối thiểu 8 ký tự" /><FormField label="Xác nhận mật khẩu" icon="lock" value={form.confirm} onChangeText={update('confirm')} secureTextEntry error={form.confirm && form.password !== form.confirm ? 'Mật khẩu xác nhận chưa khớp' : undefined} /><Pressable onPress={() => setAgreed((value) => !value)} style={styles.terms}><Checkbox checked={agreed} onPress={() => setAgreed((value) => !value)} /><Text style={styles.termsText}>Tôi đồng ý với <Text style={styles.link}>Điều khoản sử dụng</Text> và <Text style={styles.link}>Chính sách bảo mật</Text>.</Text></Pressable><Button title="Đăng ký" disabled={!valid} onPress={() => router.push({ pathname: '/auth/otp', params: { phone: form.phone, mode: 'register' } })} /></View><View style={styles.login}><Text style={styles.normal}>Đã có tài khoản? </Text><Pressable onPress={() => router.replace('/auth/login')}><Text style={styles.link}>Đăng nhập</Text></Pressable></View></AuthShell>;
}
const styles = StyleSheet.create({ form: { gap: spacing.lg }, terms: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }, termsText: { ...typography.caption, color: colors.textSecondary, flex: 1 }, link: { color: colors.primary, fontWeight: '600' }, login: { flexDirection: 'row', justifyContent: 'center', marginTop: spacing.xl }, normal: { ...typography.body, color: colors.textSecondary } });
