import { EmptyState } from '@/components/empty-state';
import { ProductImage } from '@/components/product-image';
import { Icon } from '@/components/ui/icon';
import { colors, layout, radius, spacing, typography } from '@/constants/theme';
import { useApp } from '@/state/app-context';
import type { Order, OrderStatus } from '@/types';
import { formatCurrency, orderStatusLabel } from '@/utils/format';
import { useRouter } from 'expo-router';
import { useState } from 'react';
import { FlatList, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

const filters: { label: string; value: 'ALL' | OrderStatus }[] = [{ label: 'Tất cả', value: 'ALL' }, { label: 'Chờ xác nhận', value: 'PENDING' }, { label: 'Đang xử lý', value: 'PROCESSING' }, { label: 'Đang giao', value: 'SHIPPING' }, { label: 'Đã giao', value: 'DELIVERED' }, { label: 'Đã hủy', value: 'CANCELLED' }];
function OrderCard({ order }: { order: Order }) { const router = useRouter(); const delivered = order.status === 'DELIVERED'; return <Pressable onPress={() => router.push(`/order/${order.id}`)} style={styles.card}><View style={styles.cardTop}><View><Text style={styles.code}>#{order.code}</Text><Text style={styles.date}>{order.createdAt}</Text></View><View style={[styles.status, delivered && styles.statusSuccess, order.status === 'CANCELLED' && styles.statusDanger]}><Text style={[styles.statusText, delivered && styles.statusSuccessText, order.status === 'CANCELLED' && styles.statusDangerText]}>{orderStatusLabel(order.status)}</Text></View></View><View style={styles.product}><ProductImage uri={order.items[0].product.image} style={styles.image} /><View style={styles.productCopy}><Text numberOfLines={2} style={styles.productName}>{order.items[0].product.name}</Text><Text style={styles.quantity}>{order.items.length} sản phẩm · x{order.items.reduce((sum, item) => sum + item.quantity, 0)}</Text></View></View><View style={styles.cardBottom}><View><Text style={styles.totalLabel}>Tổng thanh toán</Text><Text style={styles.total}>{formatCurrency(order.total)}</Text></View><View style={styles.detail}><Text style={styles.detailText}>Xem chi tiết</Text><Icon name="chevron-right" size={17} color={colors.primary} /></View></View></Pressable>; }
export default function OrdersScreen() { const { orders } = useApp(); const [filter, setFilter] = useState<'ALL' | OrderStatus>('ALL'); const data = filter === 'ALL' ? orders : orders.filter((order) => order.status === filter || (filter === 'PROCESSING' && order.status === 'CONFIRMED')); return <SafeAreaView edges={['top']} style={styles.safe}><View style={styles.header}><Text style={styles.title}>Đơn hàng của tôi</Text></View><View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map((item) => <Pressable key={item.value} onPress={() => setFilter(item.value)} style={[styles.filter, filter === item.value && styles.filterActive]}><Text style={[styles.filterText, filter === item.value && styles.filterTextActive]}>{item.label}</Text></Pressable>)}</ScrollView></View><FlatList data={data} keyExtractor={(item) => item.id} renderItem={({ item }) => <OrderCard order={item} />} contentContainerStyle={[styles.content, !data.length && styles.empty]} ListEmptyComponent={<EmptyState icon="receipt" title="Không có đơn hàng" description="Chưa có đơn hàng phù hợp với trạng thái này." />} /></SafeAreaView>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, header: { backgroundColor: colors.white, paddingHorizontal: spacing.lg, paddingTop: spacing.md, paddingBottom: spacing.lg }, title: { ...typography.h1, color: colors.text }, filters: { gap: spacing.sm, paddingHorizontal: spacing.lg, paddingVertical: spacing.md }, filter: { height: 38, paddingHorizontal: spacing.lg, borderRadius: radius.pill, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' }, filterActive: { backgroundColor: colors.primary, borderColor: colors.primary }, filterText: { ...typography.captionMedium, color: colors.textSecondary }, filterTextActive: { color: colors.white }, content: { width: '100%', maxWidth: layout.maxContentWidth, alignSelf: 'center', paddingHorizontal: spacing.lg, paddingBottom: spacing.xxxl, gap: spacing.md }, empty: { flexGrow: 1 }, card: { backgroundColor: colors.white, borderRadius: radius.lg, padding: spacing.lg, borderWidth: 1, borderColor: colors.border }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start' }, code: { ...typography.captionMedium, color: colors.text }, date: { ...typography.tiny, color: colors.textMuted, marginTop: 2 }, status: { paddingHorizontal: spacing.sm, paddingVertical: 5, borderRadius: radius.pill, backgroundColor: colors.warningSoft }, statusText: { ...typography.tiny, color: colors.warning }, statusSuccess: { backgroundColor: colors.successSoft }, statusSuccessText: { color: colors.success }, statusDanger: { backgroundColor: colors.dangerSoft }, statusDangerText: { color: colors.danger }, product: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.lg, paddingVertical: spacing.md, borderTopWidth: 1, borderBottomWidth: 1, borderColor: colors.border }, image: { width: 76, height: 64, borderRadius: radius.sm, backgroundColor: colors.surfaceAlt }, productCopy: { flex: 1, justifyContent: 'center' }, productName: { ...typography.bodyMedium, color: colors.text }, quantity: { ...typography.caption, color: colors.textSecondary, marginTop: 4 }, cardBottom: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingTop: spacing.md }, totalLabel: { ...typography.tiny, color: colors.textSecondary }, total: { ...typography.bodyMedium, color: colors.danger, marginTop: 1 }, detail: { flexDirection: 'row', alignItems: 'center' }, detailText: { ...typography.captionMedium, color: colors.primary } });
