import { colors, radius, spacing, typography } from '@/constants/theme';
import { banners } from '@/data/mock-data';
import { Image } from 'expo-image';
import { useRouter } from 'expo-router';
import { useCallback, useEffect, useRef, useState } from 'react';
import { FlatList, Pressable, StyleSheet, Text, useWindowDimensions, View, type ViewToken } from 'react-native';

export function BannerCarousel() {
  const router = useRouter(); const { width } = useWindowDimensions(); const itemWidth = Math.min(width - 32, 868); const ref = useRef<FlatList>(null); const [active, setActive] = useState(0);
  useEffect(() => { const timer = setInterval(() => { const next = (active + 1) % banners.length; ref.current?.scrollToIndex({ index: next, animated: true }); setActive(next); }, 5000); return () => clearInterval(timer); }, [active]);
  const onViewableItemsChanged = useCallback(({ viewableItems }: { viewableItems: ViewToken[] }) => { const index = viewableItems[0]?.index; if (typeof index === 'number') setActive(index); }, []);
  return <View><FlatList ref={ref} horizontal pagingEnabled showsHorizontalScrollIndicator={false} data={banners} keyExtractor={(item) => item.id} getItemLayout={(_, index) => ({ length: itemWidth, offset: itemWidth * index, index })} onViewableItemsChanged={onViewableItemsChanged} viewabilityConfig={{ itemVisiblePercentThreshold: 65 }} renderItem={({ item }) => {
    const dark = item.textColor === 'dark'; return <View style={[styles.slide, { width: itemWidth }]}><Image source={item.image} style={StyleSheet.absoluteFill} contentFit="cover" /><View style={[styles.tint, dark && styles.lightTint]} /><View style={styles.content}><Text style={[styles.eyebrow, dark && styles.darkText]}>{item.eyebrow}</Text><Text style={[styles.title, dark && styles.darkText]}>{item.title}</Text><Text numberOfLines={2} style={[styles.subtitle, dark && styles.darkSubtitle]}>{item.subtitle}</Text><Pressable onPress={() => router.push('/products')} style={[styles.cta, dark && styles.darkCta]}><Text style={[styles.ctaText, dark && styles.darkCtaText]}>{item.cta}</Text></Pressable></View></View>;
  }} /><View style={styles.dots}>{banners.map((item, index) => <View key={item.id} style={[styles.dot, active === index && styles.dotActive]} />)}</View></View>;
}
const styles = StyleSheet.create({ slide: { height: 194, borderRadius: radius.xl, overflow: 'hidden', position: 'relative' }, tint: { position: 'absolute', inset: 0, backgroundColor: 'rgba(2, 15, 45, 0.2)' }, lightTint: { backgroundColor: 'rgba(255,255,255,0.06)' }, content: { flex: 1, width: '58%', padding: spacing.xl, justifyContent: 'center' }, eyebrow: { ...typography.tiny, color: '#70D5FF', letterSpacing: 1 }, title: { fontSize: 23, lineHeight: 27, fontWeight: '800', color: colors.white, marginTop: 5 }, subtitle: { fontSize: 12, lineHeight: 17, color: '#D8E5FF', marginTop: spacing.sm }, darkText: { color: colors.navy }, darkSubtitle: { color: '#344054' }, cta: { alignSelf: 'flex-start', backgroundColor: colors.white, borderRadius: radius.pill, paddingHorizontal: spacing.md, paddingVertical: 7, marginTop: spacing.md }, darkCta: { backgroundColor: colors.primary }, ctaText: { ...typography.tiny, color: colors.primary }, darkCtaText: { color: colors.white }, dots: { height: 22, flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 6 }, dot: { width: 6, height: 6, borderRadius: 3, backgroundColor: colors.borderStrong }, dotActive: { width: 20, backgroundColor: colors.primary } });
