const crypto = require('node:crypto');
const bcrypt = require('bcrypt');
const env = require('../config/env');
const { trongGiaoDich } = require('../config/database');
const { mot, nhieu, chay, capNhat } = require('../repositories/co-so-du-lieu.repository');
const { phanTrang } = require('../utils/phan-trang');
const LoiUngDung = require('../utils/loi-ung-dung');
const api = require('./api.service');
const { khongCo,maTuDong,nhanVien } = api;

const listPage=async(table,q,where='1=1',params=[],order='id DESC')=>{const p=phanTrang(q);const total=(await mot(`SELECT COUNT(*) total FROM ${table} WHERE ${where}`,params)).total;return {items:await nhieu(`SELECT * FROM ${table} WHERE ${where} ORDER BY ${order} LIMIT ? OFFSET ?`,[...params,p.limit,p.offset]),pagination:{page:p.page,limit:p.limit,total,totalPages:Math.ceil(total/p.limit)}};};
const laptopMap={maSanPham:'ma_san_pham',hangLaptopId:'hang_laptop_id',danhMucId:'danh_muc_id',tenSanPham:'ten_san_pham',slug:'slug',giaNhap:'gia_nhap',giaBan:'gia_ban',giaKhuyenMai:'gia_khuyen_mai',moTa:'mo_ta',anhDaiDien:'anh_dai_dien',baoHanhThang:'bao_hanh_thang',cpu:'cpu',ramGb:'ram_gb',ssdGb:'ssd_gb',gpu:'gpu',manHinhInch:'man_hinh_inch',tanSoQuetHz:'tan_so_quet_hz',thongSoKyThuat:'thong_so_ky_thuat'};
const laptops={create:async b=>{const keys=Object.keys(laptopMap).filter(k=>b[k]!==undefined);const vals=keys.map(k=>typeof b[k]==='object'?JSON.stringify(b[k]):b[k]);const r=await chay(`INSERT INTO laptop(${keys.map(k=>laptopMap[k]).join(',')}) VALUES(${keys.map(()=>'?').join(',')})`,vals);return mot('SELECT * FROM laptop WHERE id=?',[r.insertId]);},update:async(id,b)=>{const normalized={...b};if(normalized.thongSoKyThuat&&typeof normalized.thongSoKyThuat==='object')normalized.thongSoKyThuat=JSON.stringify(normalized.thongSoKyThuat);await capNhat('laptop',id,normalized,laptopMap);return mot('SELECT * FROM laptop WHERE id=?',[id]);},status:(id,status)=>capNhat('laptop',id,{status},{status:'trang_thai'}),addImage:async(id,b)=>{if(!await mot('SELECT id FROM laptop WHERE id=?',[id]))khongCo('Laptop');if(b.laAnhChinh)await chay('UPDATE hinh_anh_laptop SET la_anh_chinh=FALSE WHERE laptop_id=?',[id]);const r=await chay('INSERT INTO hinh_anh_laptop(laptop_id,image_url,la_anh_chinh,thu_tu) VALUES(?,?,?,?)',[id,b.imageUrl,!!b.laAnhChinh,b.thuTu||0]);if(b.laAnhChinh)await chay('UPDATE laptop SET anh_dai_dien=? WHERE id=?',[b.imageUrl,id]);return mot('SELECT * FROM hinh_anh_laptop WHERE id=?',[r.insertId]);},removeImage:async(id,imageId)=>{const img=await mot('SELECT * FROM hinh_anh_laptop WHERE id=? AND laptop_id=?',[imageId,id]);if(!img)khongCo('Hinh anh');await chay('DELETE FROM hinh_anh_laptop WHERE id=?',[imageId]);if(img.la_anh_chinh)await chay('UPDATE laptop SET anh_dai_dien=NULL WHERE id=?',[id]);}};

const promoMap={maKhuyenMai:'ma_khuyen_mai',tenKhuyenMai:'ten_khuyen_mai',phamViApDung:'pham_vi_ap_dung',danhMucId:'danh_muc_id',hangLaptopId:'hang_laptop_id',loaiGiam:'loai_giam',giaTriGiam:'gia_tri_giam',donHangToiThieu:'don_hang_toi_thieu',giamToiDa:'giam_toi_da',soLuong:'so_luong',ngayBatDau:'ngay_bat_dau',ngayKetThuc:'ngay_ket_thuc',moTa:'mo_ta'};
const promotions={list:q=>listPage('khuyen_mai',q),saveDetails:async(id,ids,db)=>{if(ids!==undefined){await chay('DELETE FROM chi_tiet_khuyen_mai WHERE khuyen_mai_id=?',[id],db);for(const lid of ids)await chay('INSERT INTO chi_tiet_khuyen_mai(khuyen_mai_id,laptop_id) VALUES(?,?)',[id,lid],db);}},create:b=>trongGiaoDich(async db=>{const keys=Object.keys(promoMap).filter(k=>b[k]!==undefined);const r=await chay(`INSERT INTO khuyen_mai(${keys.map(k=>promoMap[k]).join(',')}) VALUES(${keys.map(()=>'?').join(',')})`,keys.map(k=>b[k]),db);await promotions.saveDetails(r.insertId,b.laptopIds,db);return mot('SELECT * FROM khuyen_mai WHERE id=?',[r.insertId],db);}),update:(id,b)=>trongGiaoDich(async db=>{if(Object.keys(promoMap).some(k=>b[k]!==undefined))await capNhat('khuyen_mai',id,b,promoMap,'',[],db);else if(!await mot('SELECT id FROM khuyen_mai WHERE id=?',[id],db))khongCo('Khuyen mai');await promotions.saveDetails(id,b.laptopIds,db);return mot('SELECT * FROM khuyen_mai WHERE id=?',[id],db);}),status:(id,status)=>capNhat('khuyen_mai',id,{status},{status:'trang_thai'})};

const warehouses={list:()=>nhieu('SELECT * FROM kho ORDER BY id DESC'),create:async b=>{const r=await chay('INSERT INTO kho(ma_kho,ten_kho,dia_chi,so_dien_thoai) VALUES(?,?,?,?)',[b.maKho,b.tenKho,b.diaChi||null,b.soDienThoai||null]);return mot('SELECT * FROM kho WHERE id=?',[r.insertId]);},update:async(id,b)=>{await capNhat('kho',id,b,{maKho:'ma_kho',tenKho:'ten_kho',diaChi:'dia_chi',soDienThoai:'so_dien_thoai',trangThai:'trang_thai'});return mot('SELECT * FROM kho WHERE id=?',[id]);},inventory:(q)=>{const params=[],where=[];if(q.warehouseId){where.push('t.kho_id=?');params.push(q.warehouseId);}if(q.search){where.push('(l.ten_san_pham LIKE ? OR l.ma_san_pham LIKE ?)');params.push(`%${q.search}%`,`%${q.search}%`);}return nhieu(`SELECT t.*,k.ten_kho AS tenKho,l.ten_san_pham AS tenSanPham,l.ma_san_pham AS maSanPham,(t.so_luong-t.so_luong_da_dat) AS khaDung FROM ton_kho t JOIN kho k ON k.id=t.kho_id JOIN laptop l ON l.id=t.laptop_id ${where.length?'WHERE '+where.join(' AND '):''} ORDER BY l.id,k.id`,params);},inventoryOne:(lid)=>nhieu(`SELECT t.*,k.ten_kho AS tenKho,(t.so_luong-t.so_luong_da_dat) AS khaDung FROM ton_kho t JOIN kho k ON k.id=t.kho_id WHERE t.laptop_id=?`,[lid]),low:()=>nhieu(`SELECT t.*,k.ten_kho AS tenKho,l.ten_san_pham AS tenSanPham,(t.so_luong-t.so_luong_da_dat) AS khaDung FROM ton_kho t JOIN kho k ON k.id=t.kho_id JOIN laptop l ON l.id=t.laptop_id WHERE (t.so_luong-t.so_luong_da_dat)<=t.muc_ton_toi_thieu ORDER BY khaDung`)};

const supplierMap={maNcc:'ma_ncc',tenNcc:'ten_ncc',nguoiLienHe:'nguoi_lien_he',soDienThoai:'so_dien_thoai',email:'email',diaChi:'dia_chi',ghiChu:'ghi_chu'};
const suppliers={list:q=>listPage('nha_cung_cap',q),get:async id=>(await mot('SELECT * FROM nha_cung_cap WHERE id=?',[id]))||khongCo('Nha cung cap'),create:async b=>{const keys=Object.keys(supplierMap).filter(k=>b[k]!==undefined);const r=await chay(`INSERT INTO nha_cung_cap(${keys.map(k=>supplierMap[k]).join(',')}) VALUES(${keys.map(()=>'?').join(',')})`,keys.map(k=>b[k]));return suppliers.get(r.insertId);},update:async(id,b)=>{await capNhat('nha_cung_cap',id,b,supplierMap);return suppliers.get(id);},status:(id,status)=>capNhat('nha_cung_cap',id,{status},{status:'trang_thai'})};

const imports={list:q=>listPage('phieu_nhap',q),get:async id=>{const x=await mot('SELECT * FROM phieu_nhap WHERE id=?',[id]);if(!x)khongCo('Phieu nhap');x.items=await nhieu('SELECT * FROM chi_tiet_phieu_nhap WHERE phieu_nhap_id=?',[id]);return x;},create:async(uid,b)=>{const id=await trongGiaoDich(async db=>{if(!Array.isArray(b.items)||!b.items.length)throw new LoiUngDung('Phieu nhap phai co san pham',422);const total=b.items.reduce((s,i)=>s+Number(i.soLuong)*Number(i.donGia),0);const r=await chay('INSERT INTO phieu_nhap(ma_phieu,nha_cung_cap_id,kho_id,nhan_vien_id,tong_tien,ghi_chu) VALUES(?,?,?,?,?,?)',[b.maPhieu||maTuDong('PN'),b.nhaCungCapId,b.khoId,await nhanVien(uid,db),total,b.ghiChu||null],db);for(const i of b.items)await chay('INSERT INTO chi_tiet_phieu_nhap(phieu_nhap_id,laptop_id,so_luong,don_gia) VALUES(?,?,?,?)',[r.insertId,i.laptopId,i.soLuong,i.donGia],db);return r.insertId;});return imports.get(id);},update:async(id,b)=>{await trongGiaoDich(async db=>{const x=await mot(`SELECT * FROM phieu_nhap WHERE id=? FOR UPDATE`,[id],db);if(!x)khongCo('Phieu nhap');if(x.trang_thai!=='DRAFT')throw new LoiUngDung('Chi sua duoc phieu nhap DRAFT',409);if(b.items){if(!b.items.length)throw new LoiUngDung('Phieu nhap phai co san pham',422);await chay('DELETE FROM chi_tiet_phieu_nhap WHERE phieu_nhap_id=?',[id],db);for(const i of b.items)await chay('INSERT INTO chi_tiet_phieu_nhap(phieu_nhap_id,laptop_id,so_luong,don_gia) VALUES(?,?,?,?)',[id,i.laptopId,i.soLuong,i.donGia],db);b.tongTien=b.items.reduce((s,i)=>s+Number(i.soLuong)*Number(i.donGia),0);}await capNhat('phieu_nhap',id,b,{nhaCungCapId:'nha_cung_cap_id',khoId:'kho_id',ghiChu:'ghi_chu',tongTien:'tong_tien'},'',[],db);});return imports.get(id);},complete:id=>trongGiaoDich(async db=>{const x=await mot('SELECT * FROM phieu_nhap WHERE id=? FOR UPDATE',[id],db);if(!x)khongCo('Phieu nhap');if(x.trang_thai!=='DRAFT')throw new LoiUngDung('Phieu nhap khong o trang thai DRAFT',409);const items=await nhieu('SELECT * FROM chi_tiet_phieu_nhap WHERE phieu_nhap_id=?',[id],db);for(const i of items)await chay(`INSERT INTO ton_kho(kho_id,laptop_id,so_luong) VALUES(?,?,?) ON DUPLICATE KEY UPDATE so_luong=so_luong+VALUES(so_luong)`,[x.kho_id,i.laptop_id,i.so_luong],db);await chay(`UPDATE phieu_nhap SET trang_thai='COMPLETED',ngay_nhap=NOW() WHERE id=?`,[id],db);}),cancel:async id=>{const r=await chay(`UPDATE phieu_nhap SET trang_thai='CANCELLED' WHERE id=? AND trang_thai='DRAFT'`,[id]);if(!r.affectedRows)throw new LoiUngDung('Chi huy duoc phieu nhap DRAFT',409);}};

const orderTransitions={PENDING:['CONFIRMED','CANCELLED'],CONFIRMED:['PROCESSING','CANCELLED'],PROCESSING:['SHIPPING','CANCELLED'],SHIPPING:['DELIVERED'],DELIVERED:['RETURNED'],CANCELLED:[],RETURNED:[]};
const adminOrders={list:async q=>{const where=[],params=[];if(q.status){where.push('trang_thai=?');params.push(q.status);}return listPage('don_hang',q,where.join(' AND ')||'1=1',params);},status:(uid,id,b)=>trongGiaoDich(async db=>{const o=await mot('SELECT * FROM don_hang WHERE id=? FOR UPDATE',[id],db);if(!o)khongCo('Don hang');if(!orderTransitions[o.trang_thai]?.includes(b.trangThai))throw new LoiUngDung(`Khong the chuyen ${o.trang_thai} sang ${b.trangThai}`,409);const nvid=await nhanVien(uid,db);let extra='';if(b.trangThai==='CONFIRMED')extra=',ngay_xac_nhan=NOW()';if(b.trangThai==='SHIPPING')extra=',ngay_giao=NOW()';if(b.trangThai==='DELIVERED')extra=',ngay_hoan_thanh=NOW()';await chay(`UPDATE don_hang SET trang_thai=?,nhan_vien_id=?,ghi_chu_nhan_vien=?${extra} WHERE id=?`,[b.trangThai,nvid,b.ghiChu||null,id],db);if(b.trangThai==='CANCELLED'){await api.orders.releaseStock(id,db);if(o.khuyen_mai_id)await chay('UPDATE khuyen_mai SET so_luong_da_dung=GREATEST(0,so_luong_da_dung-1) WHERE id=?',[o.khuyen_mai_id],db);}if(b.trangThai==='DELIVERED'){const items=await nhieu('SELECT laptop_id,so_luong FROM chi_tiet_don_hang WHERE don_hang_id=?',[id],db);for(const i of items){let qty=i.so_luong;const stocks=await nhieu('SELECT id,so_luong_da_dat FROM ton_kho WHERE laptop_id=? AND so_luong_da_dat>0 ORDER BY kho_id FOR UPDATE',[i.laptop_id],db);for(const s of stocks){const take=Math.min(qty,s.so_luong_da_dat);await chay('UPDATE ton_kho SET so_luong=so_luong-?,so_luong_da_dat=so_luong_da_dat-? WHERE id=?',[take,take,s.id],db);qty-=take;if(!qty)break;}}await chay(`UPDATE thanh_toan SET trang_thai='PAID',thoi_gian_thanh_toan=NOW() WHERE don_hang_id=? AND phuong_thuc='COD' AND trang_thai='PENDING'`,[id],db);}const tk=await mot('SELECT tai_khoan_id FROM khach_hang WHERE id=?',[o.khach_hang_id],db);const types={CONFIRMED:'ORDER_CONFIRMED',PROCESSING:'ORDER_CONFIRMED',SHIPPING:'ORDER_SHIPPING',DELIVERED:'ORDER_DELIVERED',CANCELLED:'ORDER_CANCELLED'};await chay(`INSERT INTO thong_bao(tai_khoan_id,loai_thong_bao,tieu_de,noi_dung,du_lieu) VALUES(?,?,?,?,JSON_OBJECT('orderId',?))`,[tk.tai_khoan_id,types[b.trangThai]||'SYSTEM','Cap nhat don hang',`Don hang chuyen sang ${b.trangThai}`,id],db);})};

const payments={customerList:async(uid,oid)=>{const kid=await api.khach(uid);if(!await mot('SELECT id FROM don_hang WHERE id=? AND khach_hang_id=?',[oid,kid]))khongCo('Don hang');return nhieu('SELECT * FROM thanh_toan WHERE don_hang_id=? ORDER BY lan_thu DESC',[oid]);},retry:(uid,oid,b)=>trongGiaoDich(async db=>{const kid=await api.khach(uid,db);const o=await mot(`SELECT * FROM don_hang WHERE id=? AND khach_hang_id=? FOR UPDATE`,[oid,kid],db);if(!o)khongCo('Don hang');if(['CANCELLED','DELIVERED','RETURNED'].includes(o.trang_thai))throw new LoiUngDung('Khong the thanh toan lai don nay',409);if(await mot(`SELECT id FROM thanh_toan WHERE don_hang_id=? AND trang_thai='PAID'`,[oid],db))throw new LoiUngDung('Don hang da thanh toan',409);const last=await mot('SELECT COALESCE(MAX(lan_thu),0) lan FROM thanh_toan WHERE don_hang_id=?',[oid],db);const r=await chay('INSERT INTO thanh_toan(don_hang_id,lan_thu,phuong_thuc,so_tien) VALUES(?,?,?,?)',[oid,last.lan+1,b.phuongThuc,o.tong_thanh_toan],db);return mot('SELECT * FROM thanh_toan WHERE id=?',[r.insertId],db);}),admin:q=>listPage('thanh_toan',q,q.status?'trang_thai=?':'1=1',q.status?[q.status]:[]),webhook:(provider,headers,b,raw)=>trongGiaoDich(async db=>{if(!env.paymentWebhookSecret)throw new LoiUngDung('Webhook chua duoc cau hinh',503);const supplied=headers['x-signature']||'';const expected=crypto.createHmac('sha256',env.paymentWebhookSecret).update(raw||JSON.stringify(b)).digest('hex');if(supplied.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(supplied),Buffer.from(expected)))throw new LoiUngDung('Chu ky webhook khong hop le',401);const p=await mot('SELECT * FROM thanh_toan WHERE id=? FOR UPDATE',[b.paymentId],db);if(!p)khongCo('Thanh toan');if(p.trang_thai==='PAID')return p;const status=b.status==='PAID'?'PAID':'FAILED';await chay('UPDATE thanh_toan SET trang_thai=?,ma_giao_dich=?,thoi_gian_thanh_toan=IF(?=\'PAID\',NOW(),NULL),noi_dung=? WHERE id=?',[status,b.transactionId,status,`${provider}: ${b.message||''}`,p.id],db);return mot('SELECT * FROM thanh_toan WHERE id=?',[p.id],db);})};
const reviews={status:(id,status)=>capNhat('danh_gia',id,{status},{status:'trang_thai'})};

const accounts={list:q=>listPage('tai_khoan',q,q.role?'vai_tro=?':'1=1',q.role?[q.role]:[]),get:async id=>(await mot(`SELECT id,vai_tro,ten_dang_nhap,email,so_dien_thoai,trang_thai,lan_dang_nhap_cuoi,created_at FROM tai_khoan WHERE id=?`,[id]))||khongCo('Tai khoan'),status:(self,id,status)=>{if(Number(self)===Number(id)&&status!=='ACTIVE')throw new LoiUngDung('Khong the khoa tai khoan dang dang nhap',409);return capNhat('tai_khoan',id,{status},{status:'trang_thai'});}};
const staffMap={hoTen:'ho_ten',chucVu:'chuc_vu',luong:'luong',ngayVaoLam:'ngay_vao_lam'};
const staff={list:q=>listPage('nhan_vien',q),get:async id=>{const r=await mot(`SELECT nv.*,tk.ten_dang_nhap,tk.email,tk.so_dien_thoai FROM nhan_vien nv JOIN tai_khoan tk ON tk.id=nv.tai_khoan_id WHERE nv.id=?`,[id]);if(!r)khongCo('Nhan vien');return r;},create:async b=>{const id=await trongGiaoDich(async db=>{const hash=await bcrypt.hash(b.matKhau,12);const tr=await chay(`INSERT INTO tai_khoan(vai_tro,ten_dang_nhap,mat_khau_hash,email,so_dien_thoai) VALUES('STAFF',?,?,?,?)`,[b.tenDangNhap,hash,b.email,b.soDienThoai||null],db);const r=await chay('INSERT INTO nhan_vien(tai_khoan_id,ma_nhan_vien,ho_ten,chuc_vu,luong,ngay_vao_lam) VALUES(?,?,?,?,?,?)',[tr.insertId,b.maNhanVien,b.hoTen,b.chucVu||null,b.luong||0,b.ngayVaoLam||null],db);return r.insertId;});return staff.get(id);},update:async(id,b)=>{await trongGiaoDich(async db=>{const nv=await mot('SELECT tai_khoan_id FROM nhan_vien WHERE id=?',[id],db);if(!nv)khongCo('Nhan vien');if(b.email!==undefined||b.soDienThoai!==undefined)await capNhat('tai_khoan',nv.tai_khoan_id,b,{email:'email',soDienThoai:'so_dien_thoai'},'',[],db);if(Object.keys(staffMap).some(k=>b[k]!==undefined))await capNhat('nhan_vien',id,b,staffMap,'',[],db);});return staff.get(id);},status:(id,status)=>trongGiaoDich(async db=>{const nv=await mot('SELECT tai_khoan_id FROM nhan_vien WHERE id=?',[id],db);if(!nv)khongCo('Nhan vien');await chay('UPDATE nhan_vien SET trang_thai=? WHERE id=?',[status,id],db);await chay('UPDATE tai_khoan SET trang_thai=? WHERE id=?',[status==='ACTIVE'?'ACTIVE':'INACTIVE',nv.tai_khoan_id],db);})};

const dashboard={summary:async()=>({revenue:(await mot(`SELECT COALESCE(SUM(tong_thanh_toan),0) value FROM don_hang WHERE trang_thai='DELIVERED'`)).value,orders:(await mot('SELECT COUNT(*) value FROM don_hang')).value,customers:(await mot('SELECT COUNT(*) value FROM khach_hang')).value,lowStock:(await mot('SELECT COUNT(*) value FROM ton_kho WHERE so_luong-so_luong_da_dat<=muc_ton_toi_thieu')).value}),revenue:q=>nhieu(`SELECT DATE(ngay_hoan_thanh) ngay,COUNT(*) soDon,SUM(tong_thanh_toan) doanhThu FROM don_hang WHERE trang_thai='DELIVERED' AND ngay_hoan_thanh BETWEEN COALESCE(?,DATE_SUB(CURDATE(),INTERVAL 30 DAY)) AND COALESCE(?,NOW()) GROUP BY DATE(ngay_hoan_thanh) ORDER BY ngay`,[q.from||null,q.to||null]),products:()=>nhieu(`SELECT l.id,l.ten_san_pham,SUM(ct.so_luong) daBan,SUM(ct.thanh_tien) doanhThu FROM chi_tiet_don_hang ct JOIN don_hang d ON d.id=ct.don_hang_id JOIN laptop l ON l.id=ct.laptop_id WHERE d.trang_thai='DELIVERED' GROUP BY l.id ORDER BY daBan DESC LIMIT 20`),orders:()=>nhieu('SELECT trang_thai trangThai,COUNT(*) soLuong FROM don_hang GROUP BY trang_thai'),inventory:()=>nhieu(`SELECT l.id,l.ten_san_pham,COALESCE(SUM(t.so_luong),0) tongTon,COALESCE(SUM(t.so_luong_da_dat),0) daDat FROM laptop l LEFT JOIN ton_kho t ON t.laptop_id=l.id GROUP BY l.id ORDER BY tongTon`)};

module.exports={laptops,promotions,warehouses,suppliers,imports,adminOrders,payments,reviews,accounts,staff,dashboard,listPage};
